[build]
  command = "echo 'no build needed'"
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-eval' 'unsafe-inline';
      connect-src 'self' https://kiqgltbzomgteccozsfg.supabase.co;
      style-src 'self' 'unsafe-inline';
      img-src 'self' data: https:;
    """
